version: '3.8'

services:
  sqlite:
    build: 
      context: ./database
      dockerfile: Dockerfile
    volumes:
      - ./database/:/db/
    healthcheck:
      test: ["CMD", "sqlite3", "/db/database.db", ".tables"]
      interval: 5s
      timeout: 30s
      retries: 5
    networks:
      - dbms_network

  backend:
    build: .
    container_name: DBMS_backend_container
    ports:
      - 8000:8000
    networks:
      - dbms_network
    depends_on:
      - sqlite
    volumes:
      - .:/app
      - ./db/:/my/sqlite/path/

networks:
  dbms_network:
    name: dbms_network